"""token added

Revision ID: 11c895b2e72d
Revises: 515fa103ac79
Create Date: 2026-03-04 09:20:04.749266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11c895b2e72d'
down_revision: Union[str, Sequence[str], None] = '515fa103ac79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite_tokens', sa.Column('token', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'invite_tokens', ['token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invite_tokens', type_='unique')
    op.drop_column('invite_tokens', 'token')
    # ### end Alembic commands ###
