"""Updated model

Revision ID: 2a55ac2c138c
Revises: 3788de12cc5a
Create Date: 2026-02-24 10:08:38.211497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a55ac2c138c'
down_revision: Union[str, Sequence[str], None] = '3788de12cc5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_teams', sa.Column('id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_user_teams_id'), 'user_teams', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_teams_id'), table_name='user_teams')
    op.drop_column('user_teams', 'id')
    # ### end Alembic commands ###
