"""Created models

Revision ID: 3788de12cc5a
Revises: eb69b656fcc6
Create Date: 2026-02-23 16:46:13.837841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3788de12cc5a'
down_revision: Union[str, Sequence[str], None] = 'eb69b656fcc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite_tokens', sa.Column('is_used', sa.Boolean(), nullable=False))
    op.drop_column('invite_tokens', 'is_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite_tokens', sa.Column('is_user', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('invite_tokens', 'is_used')
    # ### end Alembic commands ###
